import Anthropic from "@anthropic-ai/sdk";

export const AI_MODEL = process.env.AI_MODEL ?? "claude-sonnet-4-6";

let _client: Anthropic | null = null;

export function anthropic(): Anthropic {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error("ANTHROPIC_API_KEY is not configured (see Settings → Providers).");
  }
  _client ??= new Anthropic();
  return _client;
}

/** Simple token/cost log (PLAN Phase 5 guardrail). */
export function logUsage(label: string, usage: { input_tokens: number; output_tokens: number }) {
  console.log(`[ai] ${label}: in=${usage.input_tokens} out=${usage.output_tokens} model=${AI_MODEL}`);
}

export const ADVISORY_FOOTER =
  "\n\n---\n*Advisory only — verify all figures and market levels before executing. Generated by FPF FX View; not investment advice.*";
